### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Collection was modified

### ISSUE THREAD

**Issue by greco-salvatore** [sipsorcery-org/sipsorcery#1173]
We are experiencing the same exception as in #902, but i can't re-open the issue

We are actually using the SIPSorcery 6.2.4 on a Windows-x64 based environment.

```c#
2024-09-09T15:05:43.7628253+02:00  [FTL] Unhandled exception being thrown with Message: [Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at SIPSorcery.Net.RtpIceChannel.ProcessChecklist()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()] (1bacd926)
```

The exception can't be handled outside the library and is being thrown in the application who uses it, causing a crash.

I haven't checked if the problem can be solved using the suggestion in the past closed issue.
Can you look at it?
Thanks

**Comment by ChristopheI** [comment]
Could you check if the suggestion is working in your case and create a PR ?
Thx

**Comment by greco-salvatore** [comment]
Well, i can't really reproduce the crash programatically but it happens every so often. I'll keep you updated if the fix is working

**Comment by greco-salvatore** [comment]
I've just opened a pull request with the fix. Thanks

**Comment by lostmsu** [comment]
This is not really a fix. Access to the count property should be synchronized.

**Comment by DavidMartynWood** [comment]
There is no logical change in this fix, other than a decrease in performance because you're now making a copy of the list. Reading the Count property of a List will never throw an Exception (it just reads an integer value _count on the List).

**Comment by sipsorcery** [comment]
#1204 adds a lock for access to the ICE checkist which should resolve this isuse.

**Comment by sipsorcery** [comment]
Fixed on master now.
