### ISSUE TITLE
ObjectDisposedException after CancelSendAudioFromStream

### ISSUE THREAD

**Issue by davidindra** [sipsorcery-org/sipsorcery#436]
Hello,
I would like to consult a problem with SipSorcery I approached a few times. Sometimes (e.g. 1 in 1000), when there is audio playing with `AudioExtrasSource.SendAudioFromStream(stream, rate)` and then `AudioExtrasSource.CancelSendAudioFromStream()` is called, the app crashes with unhandled exception like this:
```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at SIPSorcery.Media.AudioExtrasSource.GetPcmSampleFromReader(BinaryReader binaryReader, AudioSamplingRatesEnum inputSampleRate, Int32& samplesRead)
   at SIPSorcery.Media.AudioExtrasSource.SendStreamSample(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
 --- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```
I think it has to do something with [this method](https://github.com/sipsorcery-org/sipsorcery/blob/f4a248e6d5027a3a7d629975ff942d501242f1ce/src/app/Media/Sources/AudioExtrasSource.cs#L487) (maybe the Stream is disposed while this method is already inside the `if` clause; then adding some locking or changing the control would help?), however I don't fully understand how it works.

Please, can someone take a look on this and help me solve this out?

Thank you very much, have a nice day!
D.

**Comment by davidindra** [comment]
@sipsorcery Please, can I ask which version of Sipsorcery I need to use to include this patch?
Thanks alot

**Comment by sipsorcery** [comment]
It's only available on `master` at the moment so the only way to use it is to checkout this repo and build the sipsorcery project from source.

There should be a new pre-release nuget package coming along in a little while. It's version will be `5.1.1-pre`.

**Comment by davidindra** [comment]
Thank you, have a nice day! :)
