### ISSUE TITLE
Invalid cast from 'WinRT.IInspectable' to

### ISSUE THREAD

**Issue by fallingrust** [sipsorcery-org/sipsorcery#506]
In WindowsVideoEndPoint.cs   ((IMemoryBufferByteAccess)reference).GetBuffer(out dataInBytes, out capacity) will make a crash with .net5(Invalid cast from 'WinRT.IInspectable' to)

solution：https://github.com/microsoft/CsWinRT/issues/646

**Comment by sipsorcery** [comment]
Thanks, I did spot that problem when looking at #499 but didn't track down a solution.

What about the [other problems](https://github.com/sipsorcery-org/sipsorcery/issues/499#issuecomment-860068944) mentioned in the #499 issue. Are you able to get audio and video working with `NET5`?

**Comment by fallingrust** [comment]
it work well so far,but video Render takes much resources like CPU 、memory and Video delay.  Is there a way to get yuv data,that i can render with SDL2?, Maybe I need to decode videoFrame after peerconnetion. OnVideoFrameReceived

**Comment by sipsorcery** [comment]
There are definitely optimisations that can be made in the video pipeline, #384 may be of interest.

My main focus was to get any workable solutions and do the optimisations later. So far "later" has not arrived.

**Comment by fallingrust** [comment]
i got a special problem,i got crash when i copy my solution project not .exe file to another PC ,it happened after DecodecVideo.But the old PC work well.
error message: Invalid data found when processing input
source: SIPSorceryMedia.FFmpeg
stacktrace:   at SIPSorceryMedia.FFmpeg.FFmpegInit.ThrowExceptionIfError(Int32 error)
   at SIPSorceryMedia.FFmpeg.FFmpegVideoEncoder.Decode(AVCodecID codecID, AVPacket* packet, Int32& width, Int32& height)
   at SIPSorceryMedia.FFmpeg.FFmpegVideoEncoder.Decode(AVCodecID codecID, Byte[] buffer, Int32& width, Int32& height)
   at SIPSorceryMedia.FFmpeg.FFmpegVideoEncoder.<DecodeVideo>d__22.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

**Comment by sipsorcery** [comment]
Could it be the FFmpeg binaries don't match your PC or aren't in the expected location?

The `FFmpegInit` is where the FFmpeg dll's are searched for and loaded.
