### ISSUE TITLE
SIPDNS exception on A lookup

### ISSUE THREAD

**Issue by mgsray** [sipsorcery-org/sipsorcery#555]
Encounter this error while using domain name as sip server address. The whole program works fine with IP as sip server. It's sure that the dns works fine, and I can ping xxx.xxx.com with the correct IP analyzed.
This is the error log.

[09:53:37 DBG] SIPClientUserAgent attempting to resolve xxx.xxx.com:15060.
[09:53:37 WRN] SIPDNS exception on A lookup. Query 30554 => xxx.xxx.com IN A on 223.6.6.6:53 failed with an error..
DnsClient.DnsResponseException: Query 30554 => xxx.xxx.com IN A on 223.6.6.6:53 failed with an error. ---> System.BadImageFormatException: Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
   at DnsClient.Internal.PooledBytes..ctor(Int32 length)
   at DnsClient.DnsDatagramWriter..ctor()
   at DnsClient.DnsUdpMessageHandler.<QueryAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.<WithCancellation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DnsClient.LookupClient.<ResolveQueryAsync>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.<ResolveQueryAsync>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DnsClient.LookupClient.<QueryInternalAsync>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SIPSorcery.SIP.SIPDns.<SIPLookupAsync>d__14.MoveNext()
[09:53:37 DBG] SIPClientUserAgent resolved xxx.xxx.com:15060 to udp:empty in 429.02ms.
[09:53:37 DBG] UAC commencing call to sip:CUSTOMER-VP-391@xxx.xxx.com:15060.
[09:53:38 WRN] SIPDNS exception on A lookup. Query 26616 => xxx.xxx.com IN A on 223.6.6.6:53 failed with an error..

**Comment by sipsorcery** [comment]
What OS and runtime environment is your app running in|?

The exception message looks like a .NET assembly is missing or the wrong version:

````
System.BadImageFormatException: Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
````

**Comment by mgsray** [comment]
> What OS and runtime environment is your app running in|?
> 
> The exception message looks like a .NET assembly is missing or the wrong version:
> 
> ```
> System.BadImageFormatException: Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
> ```

Windows 7 sp1, .net 4.7.2, sipsorcery 5.3.0-pre, sipsorceryMedia.windows 0.0.31-pre.

**Comment by sipsorcery** [comment]
Does the article below help?

https://stackoverflow.com/questions/63019110/could-not-load-file-or-assembly-system-buffers-version-4-0-2-0

**Comment by mgsray** [comment]
> Does the article below help?
> 
> https://stackoverflow.com/questions/63019110/could-not-load-file-or-assembly-system-buffers-version-4-0-2-0

Tried, doesn't work.

**Comment by mgsray** [comment]
@sipsorcery The problem didn't occur on my developing environment with  VS2019. The SIPDNS error occurs on the env I installed my program. The setup file is generated by VS2019 with setup project.
Hope it is helpful.

**Comment by sipsorcery** [comment]
This doesn't look like an issue with the sipsorcer code.

**Comment by mgsray** [comment]
It is related to the system.buffer.dll file corruption. Not the sipsorcery issue.
Close the issue.
