### ISSUE TITLE
Failed to initialise playback device on window

### ISSUE THREAD

**Issue by owlboo** [sipsorcery-org/sipsorcery#676]
Hi, I deployed my web application to the windows server and got this exception.
I wrote the application in .NET Core 3.1 as well as active the audio in the server.

```
[WRN] WindowsAudioEndPoint failed to initialise playback device.
NAudio.MmException: BadDeviceId calling waveOutOpen
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
   at SIPSorceryMedia.Windows.WindowsAudioEndPoint.InitPlaybackDevice(Int32 audioOutDeviceIndex, Int32 audioSinkSampleRate)
[WRN] No audio capture devices are available.
```

![image](https://user-images.githubusercontent.com/30264483/151323526-1010c3eb-29a7-42b1-abcc-592cffb167e2.png)

![image](https://user-images.githubusercontent.com/30264483/151323638-32197085-ac26-4be7-9638-aa7589e8e454.png)

OS:
`Windows Server 2016`

**Comment by sipsorcery** [comment]
I suspect you may want to use an audio session that doesn't involve  an audio device. Some examples are [AudioSendOnlyMediaSession](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/Media/AudioSendOnlyMediaSession.cs) and [MusicMediaSession](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/app/Media/MusicMediaSession.cs).

**Comment by owlboo** [comment]
Thank you for your response.
I will review the my code

**Comment by owlboo** [comment]
Hi,
I have observed the issue when calling over MusicMediaSession.
The RTP map for the audio format was not presented in the header.
Please see the following capture.

Send over MusicMediaSession

```
Via: SIP/2.0/UDP 192.168.1.4:58064;branch=z9hG4bK9f1970ccd81a4036ac2ecdd512111583;rport
To: <sip:61684968501615@IP_ADDR:6000>
From: "1111111" <sip:****@IP_ADDR>;tag=NKYFVORLPJ
Call-ID: 0de4d3ffb38a42a2b1707af287145509
CSeq: 2 INVITE
Contact: <sip:****@192.168.1.4:58064>
Max-Forwards: 70
User-Agent: sipsorcery_v5.2.3.0
Supported: replaces, norefersub, 100rel
Content-Length: 236
Content-Type: application/sdp

v=0
o=- 1680470449 0 IN IP4 127.0.0.1
s=sipsorcery
c=IN IP4 192.168.1.4
t=0 0
m=audio 58062 RTP/AVP 101
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:1099423585 cname:9c435e99-a7df-4521-938e-a329d63f76c7
```

Sending over VoipMediaSession

```
Via: SIP/2.0/UDP 192.168.1.4:65362;branch=z9hG4bKf6a54844b867400b9a36096007417c35;rport
To: <sip:61684968501615@IP_ADDR:6000>
From: "1111111" <sip:****@IP_ADDR>;tag=KSNXPIVHFQ
Call-ID: 02e234bf48f543b4bd784b1012df5fce
CSeq: 2 INVITE
Contact: <sip:****@192.168.1.4:65362>
Max-Forwards: 70
User-Agent: sipsorcery_v5.2.3.0
Supported: replaces, norefersub, 100rel
Content-Length: 308
Content-Type: application/sdp

v=0
o=- 1231031636 0 IN IP4 127.0.0.1
s=sipsorcery
c=IN IP4 192.168.1.4
t=0 0
m=audio 58624 RTP/AVP 0 8 9 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:1846378941 cname:521cef31-8ea7-4306-92e8-15bf0d71b9ee
```
My code

```
var mediaSession = new MusicMediaSession(new AudioFormat(AudioCodecsEnum.PCMU, AudioFormat.DYNAMIC_ID_MAX), AppUtil.GetIPEndPointFromHostName(pbxSettings.Host, pbxSettings.Port, false));
                mediaSession.AcceptRtpFromAny = true;
SIPCallDescriptor callDescriptor = new SIPCallDescriptor(username,
                                                                         password,
                                                                         uri,
                                                                         from,
                                                                         null,
                                                                         null,
                                                                         null,
                                                                         null,
                                                                         SIPCallDirection.Out,
                                                                         contentType,
                                                                         null,
                                                                         null);
var callTask = userAgent.Call(callDescriptor, mediaSession);
                Console.WriteLine("Call ID {0} ", userAgent.CallDescriptor.CallId);
                bool callResult = await callTask;
```
AppUtil.cs
 ```
public static IPEndPoint GetIPEndPointFromHostName(string hostName, int port, bool throwIfMoreThanOneIP)
        {
            var addresses = System.Net.Dns.GetHostAddresses(hostName);
            if (addresses.Length == 0)
            {
                throw new ArgumentException(
                    "Unable to retrieve address from specified host name.",
                    "hostName"
                );
            }
            else if (throwIfMoreThanOneIP && addresses.Length > 1)
            {
                throw new ArgumentException(
                    "There is more that one IP address to the specified host.",
                    "hostName"
                );
            }
            return new IPEndPoint(addresses[0], port);
        }
```
After having performed the call, the server returned "488 - Not Acceptable Here" with the "AudioCodecsNotMatch" error in our PBX

From VoipMediaSession

```
m=audio 58624 RTP/AVP 0 8 9 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:1846378941 cname:521cef31-8ea7-4306-92e8-15bf0d71b9ee
```

From MusicAudioSession

```
m=audio 58062 RTP/AVP 101
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:1099423585 cname:9c435e99-a7df-4521-938e-a329d63f76c7
```

**Comment by sipsorcery** [comment]
Is there any reason you aer using:

`new AudioFormat(AudioCodecsEnum.PCMU, AudioFormat.DYNAMIC_ID_MAX)`

instead of:

`new AudioFormat(AudioCodecsEnum.PCMU)`

?

It's strange to not use the standard codec ID for the well known PCMU format.

**Comment by owlboo** [comment]
Using as your recommend.

![image](https://user-images.githubusercontent.com/30264483/152712380-41f55013-bc30-4fc5-beea-e7484878aaf6.png)

Because there is no constructor with an AudioCodecsEnum argument.

![image](https://user-images.githubusercontent.com/30264483/152712890-b070a950-ca84-43b3-9519-e576880da9b2.png)

**Comment by sipsorcery** [comment]
Did that fix the problem?

**Comment by owlboo** [comment]
I can't create the AudioFormat object as there was no constructor for an AudioCodecsEnum argument that I show above.

**Comment by owlboo** [comment]
Not work for me

rtpmap for audio not present the PCMU

![image](https://user-images.githubusercontent.com/30264483/153800005-706854c0-4ccb-40ac-9150-0f769924518f.png)


```
v=0
o=- 2051758448 0 IN IP4 127.0.0.1
s=sipsorcery
c=IN IP4 10.10.0.138
t=0 0
m=audio 57298 RTP/AVP 101
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:9930490 cname:fed2def1-061e-470a-8735-129b120b3c92
```

My code

```
var mediaSession = new MusicMediaSession(new AudioFormat(SDPWellKnownMediaFormatsEnum.PCMU), new System.Net.IPEndPoint(System.Net.IPAddress.Parse(pbxSettings.Host), pbxSettings.Port));
            mediaSession.AcceptRtpFromAny = true;
```

**Comment by sipsorcery** [comment]
I dug into this a bit further and the MusicMediaSession class was broken.

I've removed it and replaced it with an alternative constructor on the VoIPMediaSession as well as an example of how to use it, see #695.

**Comment by owlboo** [comment]
I have pulled the submits on the master branch but seems like it's not working.
The constructor has an error as below.
![image](https://user-images.githubusercontent.com/30264483/156535226-99c05a6a-ee0b-40b4-8660-e164b4a6225b.png)

VoIPMediaSession class:

![image](https://user-images.githubusercontent.com/30264483/156535405-230c3e2f-7abe-4e13-804b-e9f53061c4b6.png)


Assembly: Assembly SIPSorcery, Version=6.0.6.0

**Comment by owlboo** [comment]
It's work now. Thanks you for your help.
