### ISSUE TITLE
DTLS timeout (Janus as Signaling & Media Server)

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/sipsorcery#713]
I am trying to use SIPSorcery with Janus Video Room Plugin. Sequence diagram is 

![sip_sorcery_janus_server](https://user-images.githubusercontent.com/6905164/161961324-d6776221-f00c-4200-9446-389bab428ab9.png)
 
After pc.Start().ConfigureAwait(false) getting following message:

Ice State has Changed: checking
Starting peer connection.
Ice State has Changed: connected
Peer connection state change to connecting.
Peer connection state change to closed.
Peer connection state change to failed.
{
   "janus": "hangup",
   "session_id": 7468421040542629,
   "sender": 3593859082089249,
   "reason": "DTLS timeout"
}

Would you please help me to find the issue?

PlantUML Code:
@startuml Janus_Server
	title       Janus Video Publish Message Sequence

	group Bob Join Room As Publisher
		Bob -> JanusServer: join.json
		JanusServer --> Bob: event_joined
		group Joined
			Bob -> RTCPeerConnection: RTCPeerConnection()
			RTCPeerConnection --> Bob: pc
			Bob -> Bob: CreateVideoCaptureDevice()
			group CreateVideoCaptureDevice
				Bob -> WindowsVideoEndPoint: WindowsVideoEndPoint()
				note right
					new VpxVideoEncoder()
				end note
				WindowsVideoEndPoint --> Bob: videoSource
				Bob -> VideoEncoderEndPoint: VideoEncoderEndPoint()
				VideoEncoderEndPoint --> Bob: videoSink
				Bob -> MediaStreamTrack: MediaStreamTrack()
				note right
					videoSink.GetVideoSourceFormats(), MediaStreamStatusEnum.SendRecv
				end note
				MediaStreamTrack --> Bob: videoTrack
				Bob -> RTCPeerConnection: addTrack(videoTrack)
				Bob -> RTCPeerConnection: OnVideoFrameReceived
				note right
					videoSink.GotVideoFrame
				end note
				Bob -> WindowsVideoEndPoint: OnVideoSourceEncodedSample
				note right
					pc.SendVideo
				end note
				Bob -> RTCPeerConnection: OnVideoFormatsNegotiated
				note right
					videoSink.SetVideoSourceFormat(formats.First());
					videoSource.SetVideoSourceFormat(formats.First());
				end note
				Bob -> WindowsVideoEndPoint: videoSource.OnVideoSourceRawSample
				Bob -> WindowsVideoEndPoint: videoSink.OnVideoSinkDecodedSample
			end
			Bob -> Bob: AddAudioTransceiver()
			Bob -> RTCPeerConnection: createOffer()
			Bob -> RTCPeerConnection: setLocalDescription()
			Bob -> WindowsVideoEndPoint: StartVideo()
			note right
				videoSource.StartVideo()
			end note	
			Bob -> JanusServer: offer.json
		end
		JanusServer -> Bob: answer.json
		Bob -> RTCPeerConnection: setRemoteDescription
		alt SetDescriptionResultEnum.OK
			Bob -> RTCPeerConnection: Start()
		end
	end
@enduml

**Comment by mail2mhossain** [comment]
Failed to run your demo project "JanusWebRTCStream" with the reference of master branch of SIPSorcery. Messages are same as

ICE connection state changed to connected.
Peer connection connected changed to connecting.
Peer connection connected changed to closed.
Peer connection connected changed to failed.

**Comment by mail2mhossain** [comment]
Janus Echo Test Demo
Creating peer connection.
[10:13:53 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[10:13:53 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
[10:13:53 DBG] CreateBoundUdpSocket successfully bound on [::]:52803, dual mode True.
[10:13:53 DBG] Successfully bound RTP socket [::]:52803 (dual mode True).
[10:13:53 DBG] RTPChannel for [::]:52803 started.
[10:13:53 DBG] SCTP windows size for data receiver set at 218.
[10:13:53 DBG] SCTP creating DTLS based association, is DTLS client False, ID 5000:5000:52803.
[10:13:53 DBG] RTP ICE Channel discovered 1 local candidates.
[10:13:56 DBG] RTP ICE Channel remote credentials set.
ICE connection state changed to checking.
[10:13:56 DBG] RTP ICE Channel received remote candidate: 1 1 udp 2015363327 54.163.154.72 32618 typ host generation 0
[10:13:56 DBG] RTP ICE Channel received remote candidate: 2 1 udp 1679819007 54.163.154.72 32618 typ srflx raddr 10.10.30.81 rport 32618 generation 0
Starting peer connection.
[10:13:56 DBG] Adding new candidate pair to checklist for: udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host)
[10:13:56 DBG] Existing checklist entry has higher priority, NOT adding entry for: 2 1 udp 1679819007 54.163.154.72 32618 typ srflx raddr 10.10.30.81 rport 32618 generation 0
[10:13:56 DBG] ICE RTP channel sending connectivity check for udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host) from [::]:52803 to 54.163.154.72:32618 (use candidate False).
[10:13:56 DBG] ICE RTP channel sending connectivity check for udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host) from [::]:52803 to 54.163.154.72:32618 (use candidate True).
[10:13:57 DBG] ICE RTP channel remote peer nominated entry from binding response udp:54.163.154.72:32618 (host)
[10:13:57 INF] ICE RTP channel connected after 3358ms udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host).
ICE connection state changed to connected.
Peer connection connected changed to connecting.
[10:13:57 INF] ICE connected to remote end point 54.163.154.72:32618.
[10:13:57 DBG] Starting DLS handshake with role passive.
[10:13:57 DBG] RTCPeerConnection DoDtlsHandshake started.
[10:13:57 WRN] ICE RTP channel received an unexpected STUN message 17 from 54.163.154.72:32618.
[10:13:57 DBG] DTLS commencing handshake as server.
[10:13:57 WRN] DTLS server raised unexpected alert: fatal(2), handshake_failure(40).
[10:13:57 WRN] DTLS handshake as server failed. handshake_failure(40)
Org.BouncyCastle.Crypto.Tls.TlsFatalAlert: handshake_failure(40)
   at Org.BouncyCastle.Crypto.Tls.DtlsServerProtocol.Accept(TlsServer server, DatagramTransport transport) in /_/crypto/src/crypto/tls/DtlsServerProtocol.cs:line 59
   at SIPSorcery.Net.DtlsSrtpTransport.DoHandshakeAsServer(String& handshakeError)
[10:13:57 WRN] SendRtpPacket cannot be called on a secure session before calling SetSecurityContext.
[10:13:57 WRN] RTCPeerConnection DTLS handshake failed with error handshake_failure(40).
[10:13:57 DBG] Peer connection closed with reason dtls handshake failed.
[10:13:57 DBG] RtpIceChannel for [::]:52803 closed.
[10:13:57 DBG] RTPChannel closing, RTP receiver on port 52803. Reason: dtls handshake failed.
Peer connection connected changed to closed.
Peer connection connected changed to failed.

**Comment by sipsorcery** [comment]
The interop tests between Janus and sipsorcery are currently passing, see resutls matrix on https://github.com/sipsorcery/webrtc-echoes. It might be worth checking there are any obivous differences in the way you are doing things compared to the Janus-sipsorcery integration test https://github.com/sipsorcery/webrtc-echoes/blob/master/janus/Program.cs.

Other than that DTLS issues can be a bit tricky to track down. You need to get the BouncyCastle C# source from https://www.bouncycastle.org/csharp/index.html and then reference it in the sipsorcery library instead of `Portable.BouncyCastle`. If you run your app in the Visual Studio debugger then the DTLS exception should be thrown in teh BC library and give a better idea of what's going wrong.

**Comment by mail2mhossain** [comment]
[Program.zip](https://github.com/sipsorcery-org/sipsorcery/files/8458670/Program.zip)

**Comment by mail2mhossain** [comment]
[JanusWebRTCStream.zip](https://github.com/sipsorcery-org/sipsorcery/files/8458722/JanusWebRTCStream.zip)

**Comment by mail2mhossain** [comment]
[JanusWebRTCStream.zip](https://github.com/sipsorcery-org/sipsorcery/files/8458737/JanusWebRTCStream.zip)

**Comment by rafcsoares** [comment]
> Janus Echo Test Demo Creating peer connection. [10:13:53 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0. [10:13:53 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0. [10:13:53 DBG] CreateBoundUdpSocket successfully bound on [::]:52803, dual mode True. [10:13:53 DBG] Successfully bound RTP socket [::]:52803 (dual mode True). [10:13:53 DBG] RTPChannel for [::]:52803 started. [10:13:53 DBG] SCTP windows size for data receiver set at 218. [10:13:53 DBG] SCTP creating DTLS based association, is DTLS client False, ID 5000:5000:52803. [10:13:53 DBG] RTP ICE Channel discovered 1 local candidates. [10:13:56 DBG] RTP ICE Channel remote credentials set. ICE connection state changed to checking. [10:13:56 DBG] RTP ICE Channel received remote candidate: 1 1 udp 2015363327 54.163.154.72 32618 typ host generation 0 [10:13:56 DBG] RTP ICE Channel received remote candidate: 2 1 udp 1679819007 54.163.154.72 32618 typ srflx raddr 10.10.30.81 rport 32618 generation 0 Starting peer connection. [10:13:56 DBG] Adding new candidate pair to checklist for: udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host) [10:13:56 DBG] Existing checklist entry has higher priority, NOT adding entry for: 2 1 udp 1679819007 54.163.154.72 32618 typ srflx raddr 10.10.30.81 rport 32618 generation 0 [10:13:56 DBG] ICE RTP channel sending connectivity check for udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host) from [::]:52803 to 54.163.154.72:32618 (use candidate False). [10:13:56 DBG] ICE RTP channel sending connectivity check for udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host) from [::]:52803 to 54.163.154.72:32618 (use candidate True). [10:13:57 DBG] ICE RTP channel remote peer nominated entry from binding response udp:54.163.154.72:32618 (host) [10:13:57 INF] ICE RTP channel connected after 3358ms udp:[::]:52803 (host)->udp:54.163.154.72:32618 (host). ICE connection state changed to connected. Peer connection connected changed to connecting. [10:13:57 INF] ICE connected to remote end point 54.163.154.72:32618. [10:13:57 DBG] Starting DLS handshake with role passive. [10:13:57 DBG] RTCPeerConnection DoDtlsHandshake started. [10:13:57 WRN] ICE RTP channel received an unexpected STUN message 17 from 54.163.154.72:32618. [10:13:57 DBG] DTLS commencing handshake as server. [10:13:57 WRN] DTLS server raised unexpected alert: fatal(2), handshake_failure(40). [10:13:57 WRN] DTLS handshake as server failed. handshake_failure(40) Org.BouncyCastle.Crypto.Tls.TlsFatalAlert: handshake_failure(40) at Org.BouncyCastle.Crypto.Tls.DtlsServerProtocol.Accept(TlsServer server, DatagramTransport transport) in /_/crypto/src/crypto/tls/DtlsServerProtocol.cs:line 59 at SIPSorcery.Net.DtlsSrtpTransport.DoHandshakeAsServer(String& handshakeError) [10:13:57 WRN] SendRtpPacket cannot be called on a secure session before calling SetSecurityContext. [10:13:57 WRN] RTCPeerConnection DTLS handshake failed with error handshake_failure(40). [10:13:57 DBG] Peer connection closed with reason dtls handshake failed. [10:13:57 DBG] RtpIceChannel for [::]:52803 closed. [10:13:57 DBG] RTPChannel closing, RTP receiver on port 52803. Reason: dtls handshake failed. Peer connection connected changed to closed. Peer connection connected changed to failed.


@mail2mhossain 
Buddy you need to  use new `RTCConfiguration() { X_DisableExtendedMasterSecretKey = true ; }` every time that you try to communicate with janus/kurento/openvidu

try code above on every "new RTCPeerConnection(null)" in your project
```
var config = new RTCConfiguration() 
{ 
    X_DisableExtendedMasterSecretKey = true ; 
}
RTCPeerConnection pc = new RTCPeerConnection(config);
```
