### ISSUE TITLE
SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler causes an ArgumentNullException

### ISSUE THREAD

**Issue by henrybjsoft** [sipsorcery-org/sipsorcery#815]
I found an unexpected exception thrown by SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler, caused application crash, when my server application starts a phone call sometimes.
Below is the detail stacktrace:
Unhandled exception. System.ArgumentNullException: The session description cannot be null for SetRemoteDescription. (Parameter 'sessionDescription')
 at SIPSorcery.Net.RTPSession.SetRemoteDescription(SdpType sdpType, SDP sessionDescription)
 at SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler(ISIPClientUserAgent uac, SIPResponse sipResponse)
 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
 at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by sipsorcery** [comment]
Fixed in #1224.
