### ISSUE TITLE
CRASH: SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler throws System.ArgumentNullException

### ISSUE THREAD

**Issue by henrybjsoft** [sipsorcery-org/sipsorcery#816]
In some cases SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler throws System.ArgumentNullException, and causes Server Application Crash, Detail StackTrace Logs:
Unhandled exception. System.ArgumentNullException: The session description cannot be null for SetRemoteDescription. (Parameter 'sessionDescription')
Aug 05 16:36:20 prod-or-waihu-proxy WFServer[26218]:    at SIPSorcery.Net.RTPSession.SetRemoteDescription(SdpType sdpType, SDP sessionDescription)
Aug 05 16:36:20 prod-or-waihu-proxy WFServer[26218]:    at SIPSorcery.SIP.App.SIPUserAgent.ClientCallAnsweredHandler(ISIPClientUserAgent uac, SIPResponse sipResponse)
Aug 05 16:36:20 prod-or-waihu-proxy WFServer[26218]:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
Aug 05 16:36:20 prod-or-waihu-proxy WFServer[26218]:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
Aug 05 16:36:20 prod-or-waihu-proxy WFServer[26218]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by henrybjsoft** [comment]
Sorry, duplicated post
