### ISSUE TITLE
OnRtpClosed: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ydan87** [sipsorcery-org/sipsorcery#845]
Hello,
I've been using SipSorcery, the latest version (according to NuGet at least).
Sometimes (not always), when I try to initiate a call with VoIPMediaSession I get this error between "Trying" and "Ringing" responses as part of the OnRtpClosed callback:
OnRtpClosed: Object reference not set to an instance of an object.

EDIT: Extra SipSorcery logs show this:

> [11:17:30 ERR] Exception UdpReceiver.EndReceiveFrom. System.NullReferenceException: Object reference not set to an instance of an object.
>    at SIPSorcery.net.RTP.MediaStream.OnReceiveRTPPacket(RTPHeader hdr, Int32 localPort, IPEndPoint remoteEndPoint, Byte[] buffer, VideoStream videoStream)
>    at SIPSorcery.Net.RTPSession.OnReceiveRTPPacket(Int32 localPort, IPEndPoint remoteEndPoint, Byte[] buffer)
>    at SIPSorcery.Net.RTPSession.OnReceive(Int32 localPort, IPEndPoint remoteEndPoint, Byte[] buffer)
>    at SIPSorcery.Net.RTPChannel.OnRTPPacketReceived(UdpReceiver receiver, Int32 localPort, IPEndPoint remoteEndPoint, Byte[] packet)
>    at SIPSorcery.Net.UdpReceiver.EndReceiveFrom(IAsyncResult ar)
> [11:17:30 DBG] RTPChannel closing, RTP receiver on port 18004, Control receiver on port 18005. Reason: Object reference not set to an instance of an object..

EDIT2: I see that this commit might fix it https://github.com/sipsorcery-org/sipsorcery/commit/7b400f18523794f2f688dd5a9706a44fea15e8f9 when will it be released?

What might cause this? How can I get more info on this error?
Thanks

**Comment by ydan87** [comment]
Version 6.0.11 fixed that, closing...
