### ISSUE TITLE
Race condition - Webrtc Ice connection fails sometimes

### ISSUE THREAD

**Issue by mikhaylo1** [sipsorcery-org/sipsorcery#861]
I use Sipsorcery for connecting to a remote Webrtc peer (mobile Chrome browser) at the same WIFI network.

The connection with Sipsorcery sometime fails (Race condition) if I enable VPN client at the remote peer.  However it works great if VPN is disabled
If connecting from the same local PC but using Chrome instead of Sipsorcery - it always connects fine

The issue might be related to Sipsorcery doesn't nominate all Ice candidates sometimes

**Working connection:**

```
[15:42:40 DBG] ICE RTP channel sending connectivity check for udp:[::]:54256 (host)->udp:[2a0c:5a82:1204:200:7437:c353:9266:8070]:53063 (host) from [::]:54256 to [2a0c:5a82:1204:200:7437:c353:9266:8070]:53063 (use candidate False).
[15:42:40 DBG] ICE RTP channel sending connectivity check for udp:[::]:54256 (host)->udp:192.168.100.140:59413 (host) from [::]:54256 to 192.168.100.140:59413 (use candidate False).
[15:42:40 DBG] ICE RTP channel sending connectivity check for udp:[::]:54256 (host)->udp:10.134.181.230:55467 (host) from [::]:54256 to 10.134.181.230:55467 (use candidate False).
[15:42:40 DBG] ICE RTP channel sending connectivity check for udp:[::]:54256 (host)->udp:193.23.181.40:55467 (srflx) from [::]:54256 to 193.23.181.40:55467 (use candidate False).
[15:42:40 DBG] ICE RTP channel remote peer nominated entry from binding request: udp:192.168.100.140:59413 (host).
[15:42:40 INF] ICE RTP channel connected after 1043ms udp:[::]:54256 (host)->udp:192.168.100.140:59413 (host).
[15:42:40 INF] ICE connected to remote end point 192.168.100.140:59413.
[15:42:40 DBG] Starting DLS handshake with role active.
[15:42:40 DBG] RTCPeerConnection DoDtlsHandshake started.
[15:42:40 DBG] DTLS commencing handshake as client.
[15:42:40 DBG] RTP ICE Channel received remote candidate: 2870859508 1 udp 41754367 13.39.79.62 63937 typ relay raddr 193.23.181.40 rport 55467 generation 0
[15:42:40 DBG] ICE RTP channel remote peer nominated a new candidate: udp:193.23.181.40:55467 (srflx).
[15:42:40 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:59413 (host) to udp:193.23.181.40:55467 (srflx).
[15:42:40 INF] ICE changing connected remote end point to 193.23.181.40:55467.
[15:42:40 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:55467 (host).
[15:42:40 INF] ICE RTP channel remote nominated candidate changed from udp:193.23.181.40:55467 (srflx) to udp:10.134.181.230:55467 (host).
[15:42:40 INF] ICE changing connected remote end point to 10.134.181.230:55467.
[15:42:40 DBG] ICE RTP channel remote peer nominated a new candidate: udp:193.23.181.40:55467 (srflx).
[15:42:40 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:55467 (host) to udp:193.23.181.40:55467 (srflx).
[15:42:40 INF] ICE changing connected remote end point to 193.23.181.40:55467.
[15:42:41 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:59413 (host).
[15:42:41 INF] ICE RTP channel remote nominated candidate changed from udp:193.23.181.40:55467 (srflx) to udp:192.168.100.140:59413 (host).
[15:42:41 INF] ICE changing connected remote end point to 192.168.100.140:59413.
[15:42:42 DBG] ICE RTP channel remote peer nominated a new candidate: udp:193.23.181.40:55467 (srflx).
[15:42:42 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:59413 (host) to udp:193.23.181.40:55467 (srflx).
[15:42:42 INF] ICE changing connected remote end point to 193.23.181.40:55467.
[15:42:45 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:59413 (host).
[15:42:45 INF] ICE RTP channel remote nominated candidate changed from udp:193.23.181.40:55467 (srflx) to udp:192.168.100.140:59413 (host).
[15:42:45 INF] ICE changing connected remote end point to 192.168.100.140:59413.
[15:42:46 DBG] ICE RTP channel remote peer nominated a new candidate: udp:193.23.181.40:55467 (srflx).
[15:42:46 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:59413 (host) to udp:193.23.181.40:55467 (srflx).
[15:42:46 INF] ICE changing connected remote end point to 193.23.181.40:55467.
[15:42:47 DBG] RTCPeerConnection DTLS handshake result True, is handshake complete True.
```

**Non Working connection** - the conditions are exactly the same as with the working one

```
[17:39:36 DBG] ICE RTP channel sending connectivity check for udp:[::]:52316 (host)->udp:[2a0c:5a82:1204:200:7437:c353:9266:8070]:56571 (host) from [::]:52316 to [2a0c:5a82:1204:200:7437:c353:9266:8070]:56571 (use candidate False).
[17:39:36 DBG] ICE RTP channel sending connectivity check for udp:[::]:52316 (host)->udp:192.168.100.140:42794 (host) from [::]:52316 to 192.168.100.140:42794 (use candidate False).
[17:39:36 DBG] ICE RTP channel sending connectivity check for udp:[::]:52316 (host)->udp:10.134.181.230:40919 (host) from [::]:52316 to 10.134.181.230:40919 (use candidate False).
[17:39:36 DBG] ICE RTP channel sending connectivity check for udp:[::]:52316 (host)->udp:193.23.181.40:40919 (srflx) from [::]:52316 to 193.23.181.40:40919 (use candidate False).
[17:39:36 DBG] ICE RTP channel remote peer nominated entry from binding request: udp:192.168.100.140:42794 (host).
[17:39:36 INF] ICE RTP channel connected after 904ms udp:[::]:52316 (host)->udp:192.168.100.140:42794 (host).
[17:39:36 INF] ICE connected to remote end point 192.168.100.140:42794.
[17:39:36 DBG] Starting DLS handshake with role active.
[17:39:36 DBG] RTCPeerConnection DoDtlsHandshake started.
[17:39:36 DBG] DTLS commencing handshake as client.
[17:39:36 DBG] RTP ICE Channel received remote candidate: 2870859508 1 udp 41754367 13.39.79.62 56017 typ relay raddr 193.23.181.40 rport 40919 generation 0
[17:39:36 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:36 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:36 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:37 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:37 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:37 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:37 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:37 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:37 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:37 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:37 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:37 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:38 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:38 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:38 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:38 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:38 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:38 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:38 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:38 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:38 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:39 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:39 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:39 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:39 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:39 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:39 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:39 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:39 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:39 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:40 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:40 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:40 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:40 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:40 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:40 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:40 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:40 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:40 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:41 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:41 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:41 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:41 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:41 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:41 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:41 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:41 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:41 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:42 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:42 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:42 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:42 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:42 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:42 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:42 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:42 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:42 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:43 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:43 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:43 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:43 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:43 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:43 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:43 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:43 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:43 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:44 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:44 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:44 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:44 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:44 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:44 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:44 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:44 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:44 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:45 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:45 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:45 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:45 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:45 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:45 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:46 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:46 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:46 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:46 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:46 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:46 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:46 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:46 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:46 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:47 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:47 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:47 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:47 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:47 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:47 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:47 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:47 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:47 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:48 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:48 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:48 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:48 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:48 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:48 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:48 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:48 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:48 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:49 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:49 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:49 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:49 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:49 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:49 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:49 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:49 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:49 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:50 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:50 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:50 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:50 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:50 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:50 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:50 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:50 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:50 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:51 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:51 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:51 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:51 DBG] ICE RTP channel remote peer nominated a new candidate: udp:192.168.100.140:42794 (host).
[17:39:51 INF] ICE RTP channel remote nominated candidate changed from udp:10.134.181.230:40919 (host) to udp:192.168.100.140:42794 (host).
[17:39:51 INF] ICE changing connected remote end point to 192.168.100.140:42794.
[17:39:51 DBG] ICE RTP channel remote peer nominated a new candidate: udp:10.134.181.230:40919 (host).
[17:39:51 INF] ICE RTP channel remote nominated candidate changed from udp:192.168.100.140:42794 (host) to udp:10.134.181.230:40919 (host).
[17:39:51 INF] ICE changing connected remote end point to 10.134.181.230:40919.
[17:39:56 WRN] DTLS transport timed out after 20000ms waiting for handshake from remote server.
[17:39:56 WRN] DTLS client raised unexpected alert: fatal(2), internal_error(80).
[17:39:56 WRN] DTLS handshake as client timed out waiting for handshake to complete.
Org.BouncyCastle.Crypto.Tls.TlsFatalAlert: internal_error(80)
 ---> System.TimeoutException: The operation has timed out.
   at SIPSorcery.Net.DtlsSrtpTransport.Receive(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis)
   at Org.BouncyCastle.Crypto.Tls.DtlsRecordLayer.ReceiveDatagram(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsRecordLayer.cs:line 331
   at Org.BouncyCastle.Crypto.Tls.DtlsRecordLayer.ReceiveRecord(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsRecordLayer.cs:line 530
   at Org.BouncyCastle.Crypto.Tls.DtlsRecordLayer.Receive(Byte[] buf, Int32 off, Int32 len, Int32 waitMillis) in /_/crypto/src/crypto/tls/DtlsRecordLayer.cs:line 173
   at Org.BouncyCastle.Crypto.Tls.DtlsReliableHandshake.ReceiveMessage() in /_/crypto/src/crypto/tls/DtlsReliableHandshake.cs:line 127
   at Org.BouncyCastle.Crypto.Tls.DtlsClientProtocol.ClientHandshake(ClientHandshakeState state, DtlsRecordLayer recordLayer) in /_/crypto/src/crypto/tls/DtlsClientProtocol.cs:line 94
   at Org.BouncyCastle.Crypto.Tls.DtlsClientProtocol.Connect(TlsClient client, DatagramTransport transport) in /_/crypto/src/crypto/tls/DtlsClientProtocol.cs:line 53
   --- End of inner exception stack trace ---
   at Org.BouncyCastle.Crypto.Tls.DtlsClientProtocol.Connect(TlsClient client, DatagramTransport transport) in /_/crypto/src/crypto/tls/DtlsClientProtocol.cs:line 68
   at SIPSorcery.Net.DtlsSrtpTransport.DoHandshakeAsClient(String& handshakeError)
[17:39:56 WRN] RTCPeerConnection DTLS handshake failed with error timeout.
[17:39:56 DBG] Peer connection closed with reason dtls handshake failed.
[17:39:56 DBG] RtpIceChannel for [::]:52316 closed.
[17:39:56 DBG] RTPChannel closing, RTP receiver on port 52316. Reason: dtls handshake failed.
```

From the trace you might see **srflx Ice Candidate never got nominated** on the NonWorking connection, and nominated at Working one. I assume that is the reason of the connection fail.

Attached are both logs. Would appreciate any advise

[nonWorkingConsole.log](https://github.com/sipsorcery-org/sipsorcery/files/9896422/nonWorkingConsole.log)
[workingConsole.log](https://github.com/sipsorcery-org/sipsorcery/files/9896423/workingConsole.log)

**Comment by sipsorcery** [comment]
There have been a number of improvements to the WebRTC peer negotiation that may have fixed this issue. If you're still interested and it's still a problem please feel free to re-open this issue,
