### ISSUE TITLE
FFmpegFileAndDevicesTest Error On Debian

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#959]
Can FFmpegFileAndDevicesTest run on Linux? I received this error on Debian. Is there any solution to it? I have also installed all the packages listed below.

- [SIPSorcery](https://www.nuget.org/packages/SIPSorcery)
- [SIPSorceryMedia](https://www.nuget.org/packages/SIPSorceryMedia/3.0.2)
- [SIPSorceryMedia.Encoders](https://www.nuget.org/packages/SIPSorceryMedia.Encoders/0.0.12-pre)
- [SIPSorceryMedia.FFmpeg](https://www.nuget.org/packages/SIPSorceryMedia.FFmpeg)
- [FFmpeg.AutoGen](https://www.nuget.org/packages/FFmpeg.AutoGen)

![image](https://github.com/sipsorcery-org/sipsorcery/assets/128209987/53effcfa-ca9a-4f84-9cf6-1504b872f3e8)

**Comment by ChristopheI** [comment]
it seems you don't specified a valid path to ffmpeg librairies/binaries

**Comment by nodminger** [comment]
I have provided the path from the prefix, which I obtained by running the **ffmpeg** command in the terminal. When the path is not correct, it displays an error message like 'Avcodec is not available in the given path.' When I provide the correct path, I encounter this error.

**Comment by nodminger** [comment]
@ChristopheI now I get this error after giving the correct path.

```
vboxuser@Debian:~/Desktop/LinuxTest/LinuxTest/bin/Debug/net6.0$ ./LinuxTest
WebRTC MP4 Source Demo
Starting web socket server...
Waiting for web socket connections on 0.0.0.0:8081...
Press ctrl-c to exit.
[14:37:54 DBG] Web socket client connection from 192.168.42.28:59288.
[14:37:54 WRN] No DTLS certificate is provided in the configuration
[14:37:54 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[14:37:54 DBG] CreateBoundSocket attempting to create and bind socket(s) on [::]:0 using protocol Udp.
[14:37:54 DBG] CreateBoundSocket successfully bound on [::]:39921, dual mode True.
[14:37:54 DBG] Successfully bound RTP socket [::]:39921 (dual mode True).
[14:37:54 DBG] RTPChannel for [::]:39921 started.
[14:37:54 DBG] SCTP windows size for data receiver set at 218.
[14:37:54 DBG] SCTP creating DTLS based association, is DTLS client False, ID 5000:5000:39921.
[14:37:54 DBG] Adding ICE server for stun:stun.sipsorcery.com.
[14:37:54 DBG] RTP ICE Channel discovered 1 local candidates.
[14:37:54 DBG] Adding ICE server for stun:stun.sipsorcery.com.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
   at System.String.Ctor(SByte* value)
   at SIPSorceryMedia.FFmpeg.Interop.X11.XLib.GetMonitors()
   at SIPSorceryMedia.FFmpeg.FFmpegMonitorManager.GetMonitorDevices()
   at FFmpegFileAndDevicesTest.Program.CreatePeerConnection() in /home/vboxuser/Desktop/LinuxTest/LinuxTest/Program.cs:line 178
   at SIPSorcery.Net.WebRTCWebSocketPeer.OnOpen()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted
```

**Comment by ChristopheI** [comment]
could you try using a file instead of a monitor ?

**Comment by nodminger** [comment]
It works well with video files. I am using Debian in VirtualBox. Will there be any problems because of it?

**Comment by ChristopheI** [comment]
Don't hesitate to create a PR to support Virtual environment :)

**Comment by nodminger** [comment]
Sure, but what do I need to check now? is there any solution for this?

**Comment by nodminger** [comment]
I think the below code is not able to fetch the monitors list, and maybe this is the reason I am getting error on Debian. @ChristopheI does this happened before on any of the previous versions of Sisporcery.FFmpeg?

File name: FFmpegMonitorManager.cs (in Sipsorcer.FFpeg), line: **result = XLib.GetMonitors();**
```
public unsafe class FFmpegMonitorManager
    {
        static public List<Monitor>? GetMonitorDevices()
        {
            List<Monitor>? result = null ; 

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                result = User32.GetMonitors(); 
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                result = XLib.GetMonitors();
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                result = AvFoundation.GetMonitors();
            }
            else
            {
                throw new NotSupportedException($"Cannot find adequate input format - OSArchitecture:[{RuntimeInformation.OSArchitecture}] - OSDescription:[{RuntimeInformation.OSDescription}]");
            }

            return result;
        }
    }
```

File name: XLib.cs
```
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Runtime.InteropServices;

namespace SIPSorceryMedia.FFmpeg.Interop.X11
{
    using Display = IntPtr;
    using Window = IntPtr;

    internal class XLib
    {
        private const string lib_x11 = "libX11";
        private static readonly object displayLock = new object();

        [DllImport(lib_x11, EntryPoint = "XOpenDisplay")]
        private static extern unsafe Display sys_XOpenDisplay(sbyte* display);
        public static unsafe Display XOpenDisplay(sbyte* display)
        {
            lock (displayLock)
                return sys_XOpenDisplay(display);
        }

        [DllImport(lib_x11, EntryPoint = "XCloseDisplay")]
        public static extern int XCloseDisplay(Display display);

        [DllImport(lib_x11, EntryPoint = "XDefaultRootWindow")]
        public static extern Window XDefaultRootWindow(Display display);

        [DllImport(lib_x11, EntryPoint = "XDisplayWidth")]
        public static extern int XDisplayWidth(Display display, int screenNumber);

        [DllImport(lib_x11, EntryPoint = "XDisplayHeight")]
        public static extern int XDisplayHeight(Display display, int screenNumber);


        public static List<Monitor> GetMonitors()
        {
            List<Monitor> result = new List<Monitor>();
            unsafe
            {
                IntPtr display = XLib.XOpenDisplay(null);
                IntPtr rootWindow = XLib.XDefaultRootWindow(display);
                XRRMonitorInfo* monitors = XRandr.XRRGetMonitors(display, rootWindow, true, out int count);
                for (int i = 0; i < count; i++)
                {
                    XRRMonitorInfo monitor = monitors[i];
                    string nameAddition = monitor.Name == null ? "" : $" ({new string(monitor.Name)})";

                    Monitor m = new Monitor
                    {
                        Name = $"{i}{nameAddition}",
                        Path = ":0",
                        Rect = new Rectangle(monitor.X, monitor.Y, monitor.Width, monitor.Height),
                        Primary = monitor.Primary > 0,
                    };
                    result.Add(m);
                }
            }
            return result;
        }

    }
}

```

**Comment by nodminger** [comment]
The code works when the arguments are given directly.
