### ISSUE TITLE
Getting System.Net.Sockets Error On MacOS

### ISSUE THREAD

**Issue by nodminger** [sipsorcery-org/sipsorcery#963]
Getting this error when I run FFmpegFileAndDeviceTest on macOS Monterey.

```
[14:34:55 WRN] A socket 'receive from' attempt on a dual mode socket failed (dual mode RTP sockets will not be used) with a platform exception This platform does not support packet information for dual-mode sockets.  If packet information is not required, use Socket.Receive.  If packet information is required set Socket.DualMode to false.
System.PlatformNotSupportedException: This platform does not support packet information for dual-mode sockets.  If packet information is not required, use Socket.Receive.  If packet information is required set Socket.DualMode to false.
   at System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(Socket socket)
   at System.Net.Sockets.Socket.ReceiveFromAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveFromAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveFromAsync(Memory`1 buffer, SocketFlags socketFlags, EndPoint remoteEndPoint, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.BeginReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP, AsyncCallback callback, Object state)
   at SIPSorcery.Sys.NetServices.DoCheckSupportsDualModeIPv4PacketInfo()
```

**Comment by ChristopheI** [comment]
Which version of .Net are you using ? (try using .Net 6.0 at least)
Which version of SipSorcery are you using ?

**Comment by nodminger** [comment]
I tried using .Net 6 and 7. I am using the default SipSorcery provided at [https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/tree/master/test/FFmpegFileAndDevicesTest](https://github.com/sipsorcery-org/SIPSorceryMedia.FFmpeg/tree/master/test/FFmpegFileAndDevicesTest). I didn't install anything new.

**Comment by nodminger** [comment]
I tried using Sipsorcery on a Mac, and it worked. It seems that it didn't work due to the Virtual Machine I used earlier.
